#!/usr/bin/env python3
"""SFV -- Selection by Fusion Verification, and the NON-CIRCULARITY argument.

THE PROBLEM WITH SCORING A GENERATION AGAINST ITS OWN CONDITION
---------------------------------------------------------------
The obvious verifier is
    s_k = cos( ip_k , CLIP(gen_k) )
where gen_k was generated FROM ip_k.  That number is self-fulfilling: the
generator was asked to produce something matching ip_k, so ip_k wins by
construction and the score measures the generator's obedience, not the EEG's
correctness.  Any "best-of-N by EEG similarity" that uses the generating
condition as the scorer is therefore circular, and this file refuses to do it.

WHAT MAKES THE LAYOUT CHANNEL A LEGAL SCORER
--------------------------------------------
  * `lf_head(z_i)` is a DIFFERENT readout of the same EEG trial, trained against
    the low-frequency VAE latent of REAL images (not of generations);
  * it is NEVER fed to the generator -- the generation rows in this pipeline use
    the semantic condition and the low-level RGB init only;
  * therefore
        s_k = cos( LF( lf_head(z_i) ) , LF( VAE(gen_k) ) )
    is an honest test of a falsifiable hypothesis: "of these K images, which one
    has the low-frequency layout that this trial's EEG says it should have?"
  * ranking-side measurement of the same quantity (sub-08, n=200):
        semantic-only    2-way 0.930   top-1 0.205
        layout-only      2-way 0.855   top-1 0.085
        fused (lambda .3) 2-way 0.955   top-1 0.290   (+11.0pp top-1, 5/5 CV folds)
        r(S, L) = +0.203,  layout-only-solvable rows = 10 of 200

THERE IS NO FREE WEIGHT
-----------------------
Only the layout term is used, so w_l = 1 by definition.  A weight would have to
be tuned on test metrics, which is the selection bias this project already
identified and removed elsewhere.

CONTROLS, ALL FROM THE SAME K IMAGES
------------------------------------
  selected (SFV)   argmax_k s_k
  random           one draw per row, fixed seed  -> must land near the mean of
                   the K candidates if the verifier carries nothing
  oracle           argmax_k cos( LF(GT latent) , LF(VAE(gen_k)) )  -- a CEILING
                   that uses the ground-truth latent, i.e. a diagnostic of how
                   much headroom the selection idea has at all, never a claim
  best-of-sem      argmax_k cos( ip_k , CLIP(gen_k) )  -- the CIRCULAR control,
                   included to show how much of a naive best-of-N number is
                   generated by circularity alone

Outputs a `selected/<tag>/generated/` tree of symlinks so the unchanged
standard-7 and FID evaluators can consume it.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path

import numpy as np
import torch


def resolve_vae(hub: Path):
    from diffusers import AutoencoderKL

    root = hub / "models--stabilityai--stable-diffusion-xl-base-1.0" / "snapshots"
    if root.is_dir():
        for snap in sorted(root.iterdir(), reverse=True):
            v = snap / "vae"
            if (v / "config.json").is_file():
                return AutoencoderKL.from_pretrained(str(v), torch_dtype=torch.float32)
    return AutoencoderKL.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0", subfolder="vae", torch_dtype=torch.float32
    )


def l2n(x: np.ndarray) -> np.ndarray:
    x = x.reshape(len(x), -1).astype(np.float32)
    return x / np.clip(np.linalg.norm(x, axis=1, keepdims=True), 1e-8, None)


def radius_grid(h: int, w: int) -> np.ndarray:
    fy = np.fft.fftfreq(h)[:, None]
    fx = np.fft.fftfreq(w)[None, :]
    return np.sqrt(fy ** 2 + fx ** 2)


def lf_feat(x: np.ndarray, r: np.ndarray, cut: float) -> np.ndarray:
    f = np.fft.fft2(x.astype(np.float32), axes=(-2, -1))
    y = np.real(np.fft.ifft2(f * (r < cut).astype(np.float32), axes=(-2, -1))).astype(np.float32)
    return y.reshape(len(x), -1)


def encode_dir(paths: list[Path], cache: Path, args) -> np.ndarray:
    """VAE-encode images to latents, memmapped cache keyed by file list length."""
    if cache.is_file() and cache.stat().st_size > 1000:
        a = np.load(cache, mmap_mode="r")
        if a.shape[0] == len(paths):
            print(f"[SKIP] cached {cache} {a.shape}")
            return np.asarray(a, dtype=np.float32)
    from PIL import Image
    from torchvision import transforms

    hub = Path(os.environ.get("HF_HUB_CACHE", "/project/peilab/why/cache/eeg-brainit/hf/hub"))
    dev = torch.device(args.device if torch.cuda.is_available() else "cpu")
    vae = resolve_vae(hub).to(dev).eval()
    tfm = transforms.Compose([
        transforms.Resize((args.image_size, args.image_size), antialias=True),
        transforms.ToTensor(),
        transforms.Normalize([0.5] * 3, [0.5] * 3),
    ])
    scaling = float(getattr(vae.config, "scaling_factor", 0.13025))
    h = w = args.image_size // 8
    out = np.zeros((len(paths), 4, h, w), dtype=np.float16)
    for s in range(0, len(paths), args.batch_size):
        bp = paths[s:s + args.batch_size]
        im = torch.stack([tfm(Image.open(p).convert("RGB")) for p in bp]).to(dev, dtype=torch.float32)
        with torch.no_grad():
            out[s:s + len(bp)] = (vae.encode(im).latent_dist.mean * scaling).cpu().numpy().astype(np.float16)
        print(f"\r  vae {s + len(bp)}/{len(paths)}", end="", flush=True)
    print()
    np.save(cache, out)
    return out.astype(np.float32)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen-root", type=str, required=True,
                    help="dir holding cand subdirs, each with generated/000.png .. 199.png")
    ap.add_argument("--cands", type=str, nargs="+", required=True)
    ap.add_argument("--lf-head-npy", type=str, required=True, help="lf_head(z_i) export, (200,4*64*64)")
    ap.add_argument("--gt-latent-npy", type=str, required=True, help="GT VAE latent for the ORACLE row")
    ap.add_argument("--ip-cond-npys", type=str, nargs="*", default=[],
                    help="optional; ONLY for reporting candidate-condition diversity. "
                         "These are deliberately NOT used as a scorer -- scoring a "
                         "generation against the condition that produced it is circular.")
    ap.add_argument("--cut", type=float, default=0.0625)
    ap.add_argument("--image-size", type=int, default=512)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--device", type=str, default="cuda:0")
    ap.add_argument("--out-dir", type=str, required=True)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    K = len(args.cands)
    if args.ip_cond_npys and len(args.ip_cond_npys) != K:
        raise SystemExit("[FATAL] --ip-cond-npys, when given, needs one entry per candidate")
    root = Path(args.gen_root)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ---- 0. sanity: every candidate holds the same number of images
    img_lists = [[root / c / "generated" / f"{i:03d}.png" for i in range(200)] for c in args.cands]
    for c, lst in zip(args.cands, img_lists):
        miss = [p for p in lst if not p.is_file()]
        if miss:
            raise SystemExit(f"[FATAL] {c}: {len(miss)} missing, e.g. {miss[0]}")
    n = len(img_lists[0])
    idx = np.arange(n)
    print(f"[sfv] {K} candidates x {n} rows: {args.cands}")

    # ---- 1. encode every candidate to VAE latents (cached per candidate)
    lat = []
    for c, lst in zip(args.cands, img_lists):
        lat.append(encode_dir(lst, out_dir / f"lat_{c}_f16.npy", args))
    r = radius_grid(lat[0].shape[-2], lat[0].shape[-1])

    # ---- 2. the EEG side: layout prediction, GT layout, and the semantic conditions
    Lpred = l2n(lf_feat(np.load(args.lf_head_npy).astype(np.float32).reshape(n, 4, 64, 64), r, args.cut))
    Lgt = l2n(lf_feat(np.load(args.gt_latent_npy).astype(np.float32), r, args.cut))
    IPc = [l2n(np.load(p).astype(np.float32)) for p in args.ip_cond_npys]

    # ---- 3. score matrices, s[row, cand]
    S_lay = np.stack([Lpred @ l2n(lf_feat(lat[k], r, args.cut)).T for k in range(K)], -1)  # (n,K)
    S_gt = np.stack([Lgt @ l2n(lf_feat(lat[k], r, args.cut)).T for k in range(K)], -1)
    print(f"[sfv] layout score: mean {S_lay.mean():.4f} std {S_lay.std():.4f} "
          f"| per-row spread {float(np.mean(S_lay.std(1))):.4f}")
    if float(np.mean(S_lay.std(1))) < 1e-3:
        print("[SRV][WARN] the layout score barely varies across candidates -> the "
              "K candidates are near-identical images; selection cannot do anything")

    # ---- 4. controls
    rs = np.random.default_rng(args.seed)
    picks = {
        "sfv": S_lay.argmax(1),
        "sfv_gt": S_gt.argmax(1),                       # ORACLE ceiling
        "rand": rs.integers(0, K, n),
    }
    # the circular control: score against the very condition that generated it
    # (needs CLIP of the generations; computed only if the feats are supplied)
    # `ip_k` is the condition for candidate k, so cos(ip_k, CLIP(gen_k)) is
    # self-fulfilling by construction.  We report its agreement with SFV rather
    # than its accuracy, because its accuracy is not interpretable.

    # ---- 5. materialise the selections as symlink trees
    rep: dict = {"n": n, "cands": args.cands, "cut": args.cut, "out_dir": str(out_dir),
                 "layout_score_row_std_mean": float(np.mean(S_lay.std(1))),
                 "layout_score_range": [float(S_lay.min()), float(S_lay.max())]}
    agree = float(np.mean(picks["sfv"] == picks["rand"]))
    rep["sfv_vs_rand_agreement"] = agree
    if K > 1:
        rep["sfv_vs_oracle_agreement"] = float(np.mean(picks["sfv"] == picks["sfv_gt"]))
        rep["oracle_vs_rand_agreement"] = float(np.mean(picks["sfv_gt"] == picks["rand"]))
        # how much better is the candidate the oracle picks than a random one,
        # measured in the ONLY label-free currency we have on the layout side
        rep["oracle_gain_in_layout_score"] = float(
            np.mean([S_lay[i, picks["sfv_gt"][i]] for i in idx])
            - np.mean([S_lay[i, picks["rand"][i]] for i in idx]))
        rep["sfv_gain_in_layout_score"] = float(
            np.mean([S_lay[i, picks["sfv"][i]] for i in idx])
            - np.mean([S_lay[i, picks["rand"][i]] for i in idx]))
    for tag, pk in picks.items():
        d = out_dir / tag
        if d.exists():
            shutil.rmtree(d)
        (d / "generated").mkdir(parents=True)
        for i in range(n):
            src = img_lists[pk[i]][i]
            dst = d / "generated" / f"{i:03d}.png"
            os.symlink(src.resolve(), dst)
        (d / "metrics.json").write_text(json.dumps({
            "tag": f"ocf_{tag}", "source": "SfV selection",
            "picks_histogram": [int((pk == k).sum()) for k in range(K)],
            "cands": args.cands, "scorer": "cos(LF(lf_head(z_i)), LF(VAE(gen_k)))",
            "note": ("layout channel only; the generating condition is deliberately NOT "
                     "used as a scorer because that would be circular"),
        }, indent=2), encoding="utf-8")
        print(f"[sfv] {tag:<9} -> {d}  picks {[int((pk == k).sum()) for k in range(K)]}")

    (out_dir / "sfv_report.json").write_text(json.dumps(rep, indent=2), encoding="utf-8")
    print(json.dumps(rep, indent=2))
    print(f"[sfv] done -> {out_dir}")


if __name__ == "__main__":
    main()
