#!/usr/bin/env bash
# Submit the G2 overnight extension: multi-fold LOSO + one evaluation pass.
#
#   array  : subjects 1-7,9,10 (sub-08 is already covered by the first G2 job)
#   eval   : dependent single job, afterany on the array so one failed fold cannot
#            block the other eight from being evaluated
#
# Everything downstream of the shared image-side stage is reused: captions and targets
# are produced once by the first job and read by every fold.
set -euo pipefail

NB_ROOT="${NB_ROOT:-/project/peilab/why/NeuroBridge}"
OUT="${OUT:-${NB_ROOT}/outputs/g2}"
LOG_DIR="${NB_ROOT}/outputs/slurm"
SUBJECTS="${SUBJECTS:-1-7,9,10}"
EPOCHS="${EPOCHS:-40}"
GEN_VARIANTS="${GEN_VARIANTS:-direct,cfm0}"
# Captions are still being generated by the first job, and it can be preempted, so
# starting the array immediately would park nine GPUs in a polling loop. --begin
# keeps them queued until the shared targets are expected to exist; run_g2_multi.sh
# still polls, so slippage is handled rather than fatal.
BEGIN_DELAY="${BEGIN_DELAY:-120}"
mkdir -p "${LOG_DIR}" "${OUT}"

ARRAY_ID=$(sbatch --parsable \
  --array="${SUBJECTS}" \
  --begin="now+${BEGIN_DELAY}minutes" \
  --export=ALL,OUT="${OUT}",EPOCHS="${EPOCHS}",GEN_VARIANTS="${GEN_VARIANTS}" \
  "${NB_ROOT}/slurm/g2_multi.sbatch")
echo "[OK] array job ${ARRAY_ID} (subjects ${SUBJECTS}, begin now+${BEGIN_DELAY}min)"

EVAL_ID=$(sbatch --parsable \
  --dependency=afterany:"${ARRAY_ID}" \
  --export=ALL,OUT="${OUT}" \
  "${NB_ROOT}/slurm/g2_eval.sbatch")
echo "[OK] eval job ${EVAL_ID} (afterany ${ARRAY_ID})"

echo "${ARRAY_ID}" > "${OUT}/g2_multi.arrayid"
echo "${EVAL_ID}" > "${OUT}/g2_eval.jobid"

cat > "${LOG_DIR}/g2_multi.submit.json" <<EOF
{
  "pipeline": "g2_multi",
  "array_job": "${ARRAY_ID}",
  "eval_job": "${EVAL_ID}",
  "subjects": "${SUBJECTS}",
  "submitted": "$(date -Iseconds)",
  "epochs": "${EPOCHS}",
  "variants": "${GEN_VARIANTS}",
  "goal": "Extend G2 from one held-out subject to a full leave-one-subject-out sweep. Every fold trains the granularity-factorised parallel dual tower on the other 9 subjects (held-out subject never seen), generates with its own conditions, and all folds are evaluated in a single pass so the GT feature cache is shared and results.json is not raced.",
  "shared_stages": "VLM captions and granularity targets are image-side and subject-independent; they are produced once and read by all folds",
  "pooled_protocol": "pooled FID = fake from all 10 folds concatenated vs the 200 unique test images (canonical SOTA protocol)",
  "resumability": "g2_train.py writes <out>/last.pth every epoch and resumes from it; generation skips finished rows; hence 18h wall limit is safe",
  "note": "sub-08's intra-subject rows from the first job are kept as separate rows (protocol=intra) and are never pooled with the LOSO rows"
}
EOF

echo
cat "${LOG_DIR}/g2_multi.submit.json"
echo
echo "[INFO] monitor with: squeue -u \$USER; tail -f ${LOG_DIR}/g2-multi-${ARRAY_ID}_*.out"
