#!/usr/bin/env bash
# NW-Retrieval sub-08: the full axis sweep, probe first, one job.
#
# DO NOT EDIT THIS FILE (or run_arm.sh) WHILE A JOB IS RUNNING IT. bash reads shell
# scripts incrementally by byte offset, so an edit mid-run makes the next read land
# in the middle of a changed region and the job dies on a bogus syntax error -- which
# is how the 595261 summary phase was lost while its arm results survived on disk.
# Re-run the summary with scripts/nwret/summarize.py instead of resubmitting.
#
# Steps
# -----
#   P0  ridge floor                        closed form; the number every arm must beat
#   P1  per-layer CLIP features            one forward pass yields all 33 targets
#   P2  probe: which layer is most alignable?   closed-form ridge, seconds per layer
#   P3  alignment-target scan              extend the confirmed lever (block22/28)
#   P4  image-side multi-layer alignment   doc phase 2, on the alignment-target axis
#   P5  EEG-encoder depth                  doc phase 1, on the encoder axis
#   P6  EEG-side multi-layer fusion        doc phase 2, uniform then routed
#   P7  tokenisation variants              EEGiT prices this as a large lever
#   P8  leaderboard + the specific answers
#
# There are TWO independent layer axes and the first sweep only moved one of them.
# `--target-layer` is which layer of the FROZEN IMAGE tower the EEG must match;
# `--layers` is which depth of the EEG ENCODER emits the aligned feature. The doc's
# phase 1 is written about the second, and the first turned out to be worth +13.00
# test Top-1 (34.00 at block26 vs 21.00 at the final layer, everything else fixed).
# Both are swept here, and the leaderboard labels them separately.
#
# Ordering principle: highest information per GPU-minute first, so a run that is cut
# short by the time guard still yields the most valuable results. Arms whose result
# JSON is already complete are skipped, so re-submitting continues rather than redoes.
#
# Leak-free discipline: every selection (checkpoint, alignment layer, fusion weights,
# lambda) uses a concept-level holdout of *training* concepts. Test is scored once per
# arm and is never an input to any decision.
#
# NOT in this run, deliberately:
#   * CLIP ViT-H-14 / DINOv2-L backbones. ViT-H-14 needs ~7.4x ViT-B/16's activation
#     memory, so batch must drop from 512 to ~64, which confounds "bigger backbone"
#     with "different batch size", and costs ~2h per arm. Needs gradient checkpointing
#     or bf16 (plus a same-precision ViT-B control) to answer honestly.
#   * The DINOv2 structural branch. Its target per docs section 5.2 is SDXL VAE
#     latents, not vision features; testing it against CLIP features would contradict
#     3.1's own reasoning. That is a separate axis (VAE regression) and a separate job.
set -uo pipefail

ROOT="/project/peilab/why/eeg-retrieval"
cd "${ROOT}"

PY="${PYTHON:-/project/peilab/why/eeg-brainit/.venv/bin/python}"
SUBJ="${SUBJ:-8}"
EPOCHS="${EPOCHS:-50}"
export PYTHON OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
export HF_HOME="${HF_HOME:-/project/peilab/why/cache/eeg-brainit/hf}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-${HF_HOME}/hub}"
export TORCH_HOME="${TORCH_HOME:-/project/peilab/why/cache/eeg-brainit/torch}"
export OPENCLIP_CACHE_DIR="${OPENCLIP_CACHE_DIR:-${HF_HOME}/open_clip}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-/project/peilab/why/cache/xdg}"
export HOME="${XDG_CACHE_HOME}"      # no library may write to /home

OUT="${ROOT}/outputs/sub$(printf '%02d' "${SUBJ}")"
LOGS="${ROOT}/outputs/logs"
FEAT="${FEAT:-${ROOT}/outputs/features/clip_h14_layers}"
mkdir -p "${OUT}" "${LOGS}" outputs/slurm

source "${ROOT}/scripts/lib_pipeline_guard.sh"

BUDGET_S=$(( ${PIPELINE_HOURS:-10} * 3600 ))
RESERVE_S=$(( 20 * 60 ))
guard::init "${BUDGET_S}" "${RESERVE_S}" "$(guard::now)"

remaining()     { guard::remaining; }
have_time_for() { guard::have_time_for "$1"; }
elapsed_h()    { guard::elapsed_h; }

# ------------------------------------------------------------------ helpers
# No result-file bookkeeping array: summarize.py scans the output directory, and an
# array that is appended to but never read reads as though something consumes it.
EXTRA=""
PROBE_LAYER=""

# PROBE_LAYER must be forwarded here, not just to the training call: run_arm.sh puts
# it in the tag, so computing the tag without it yields `align_unset` while train.py
# writes `align_block26_result.json`, desynchronising the resume check from the file
# it is meant to find.
tag_of() { ARM=tag PROBE_LAYER="${PROBE_LAYER}" bash scripts/run_arm.sh "$1"; }
note_of() { ARM=note bash scripts/run_arm.sh "$1"; }

arm_done() {
  local tag
  tag="$(tag_of "$1")"
  [ -n "${tag}" ] || return 1
  "${PY}" - "$OUT/${tag}_result.json" <<'PY' 2>/dev/null
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    ok = "test" in d and d["test"].get("n", 0) > 0
except Exception:
    ok = False
sys.exit(0 if ok else 1)
PY
}

# Minimum seconds each arm is assumed to need, for the time guard. Measured, not
# guessed: PA ran 1098s wall for 28 epochs at 38s/epoch (train 36s + val 2-7s), and
# the epoch loop stops on patience rather than running the full 50.
declare -A MIN_S=(
  [F1]=1200 [F2]=1200 [PA]=1200
  [T22]=1200 [T28]=1200
  [MTmean]=1400 [MTrouted]=1400
  [E04]=1100 [E08]=1100
  [FEU]=1400 [FER]=1400
  [K49]=1100 [K98]=1100
)

run_arm() {
  local arm="$1" tag min_s
  tag="$(tag_of "${arm}")"
  min_s="${MIN_S[$arm]:-1200}"
  local log="${LOGS}/${tag}.log"
  if arm_done "${arm}"; then
    echo "[skip ] ${arm} (${tag}: result already complete)"
    return 0
  fi
  if ! have_time_for "${min_s}"; then
    echo "[defer] ${arm} (${tag}: needs ~${min_s}s, $(remaining)s left)"
    return 100
  fi
  echo
  echo "=================================================================="
  echo "[arm  ] ${arm} -- $(note_of "${arm}")"
  echo "        tag=${tag}  ~${min_s}s  $(remaining)s left  ${EPOCHS} epochs"
  echo "=================================================================="
  ARM="${arm}" SUBJ="${SUBJ}" EPOCHS="${EPOCHS}" EXTRA="${EXTRA}" \
    PROBE_LAYER="${PROBE_LAYER}" bash scripts/run_arm.sh 2>&1 | tee "${log}"
  local rc=${PIPESTATUS[0]}
  echo "[arm  ] ${arm} rc=${rc} @ $(date -Iseconds)"
  return 0
}

# Runs a phase (list of arms) and reports what was deferred, without aborting the
# job: a deferred arm is a scheduling fact, not an error, and the summary states it.
phase() {
  local name="$1"; shift
  echo
  echo "########## ${name} @ $(date -Iseconds) ##########"
  local deferred=0
  for a in "$@"; do
    run_arm "${a}"
    [ $? -eq 100 ] && deferred=$(( deferred + 1 ))
  done
  [ "${deferred}" -gt 0 ] && echo "[${name}] ${deferred} arm(s) deferred by the time guard"
  return 0
}

echo "########## NW-Retrieval sub-08 FULL SWEEP @ $(date -Iseconds) ##########"
echo "[cfg  ] subject=${SUBJ} epochs=${EPOCHS} budget=${PIPELINE_HOURS:-10}h"

# ------------------------------------------------------------------ sanity
"${PY}" - <<'PY' || { echo "[FATAL] environment check failed"; exit 1; }
import sys, torch
if not torch.cuda.is_available():
    print("[FATAL] CUDA unavailable -- the login node has no GPU, submit via sbatch")
    sys.exit(1)
p = torch.cuda.get_device_properties(0)
print(f"[env  ] {torch.cuda.get_device_name(0)}  {p.total_memory/2**30:.0f} GiB  torch={torch.__version__}")
PY

"${PY}" scripts/test_fixes.py || { echo "[FATAL] fix regression tests failed"; exit 1; }

# Validate every arm's real flag list before spending GPU time on any of them. Does
# not duplicate the flag lists, so it cannot drift out of sync with run_arm.sh.
echo
echo "[gate ] arm flag dry run (no GPU; validates each arm's actual flags)"
bash scripts/test_pipeline_logic.sh >/tmp/nwret_arm_dry.log 2>&1
DRY_RC=$?
tail -4 /tmp/nwret_arm_dry.log
if [ "${DRY_RC}" != "0" ]; then
  echo "[FATAL] arm/pipeline dry run failed; refusing to start with a bad arm"
  exit 1
fi

"${PY}" - <<'PY' || { echo "[FATAL] tokenizer/metric precheck failed"; exit 1; }
import sys, json, numpy as np, torch
sys.path.insert(0, "scripts"); sys.path.insert(0, "third_party/SAMGA")
from nwret import config
from nwret.tokenizer import EEGTokenizer
from nwret.metrics import retrieve_all as mine

info = json.loads((config.EEG_DIR / "info.json").read_text())
ch = info["ch_names"]
for ntw, want in ((1, 49), (2, 98), (4, 196)):
    tk = EEGTokenizer(ch, d_model=768, grid_h=7, grid_w=7, n_time_windows=ntw)
    assert tk.n_tokens == want, f"ntw={ntw} -> {tk.n_tokens} tokens, expected {want}"
    out = tk(torch.randn(2, 63, 250))
    assert tuple(out.shape) == (2, want, 768), out.shape
    assert np.allclose(tk.interp.sum(1).numpy(), 1, atol=1e-4)
print("[check] tokenizer: 1/2/4 windows -> 49/98/196 tokens, all shape-correct")

try:
    from module.util import retrieve_all as theirs
    rng = np.random.default_rng(0)
    a, b = rng.normal(size=(200, 64)), rng.normal(size=(200, 64))
    b[:50] = a[:50] + 0.1 * rng.normal(size=(50, 64))
    assert mine(a, b) == theirs(a, b, True), (mine(a, b), theirs(a, b, True))
    print("[check] metric identical to SAMGA module/util.py")
except ImportError:
    print("[check] SAMGA reference not importable; using local metric only")
PY

# ------------------------------------------------------------------ P0: floor
if [ -f "${OUT}/baseline_ridge.json" ]; then
  echo "[P0   ] ridge baseline present; reusing"
else
  echo
  echo "=================================================================="
  echo "[P0   ] ridge baseline (closed-form linear EEG -> image features)"
  echo "=================================================================="
  "${PY}" -u scripts/nwret/baseline_ridge.py --subject "${SUBJ}" \
    --channels occipito_parietal --out "${OUT}/baseline_ridge.json" 2>&1 \
    | tee "${LOGS}/baseline_ridge.log" || true
fi
RIDGE="$("${PY}" -c "
import json
try:
    print(f\"{json.load(open('${OUT}/baseline_ridge.json'))['test']['top1']:.2f}\")
except Exception:
    print('n/a')")"
echo "[P0   ] ridge floor: ${RIDGE} test Top-1 (this is the floor the deep arms must clear)"

# ------------------------------------------------------------------ P1: layers
# One forward pass, all 33 targets. Verification against the shipped features is a
# hard gate: those arrays define the concept and image-slot order that the EEG uses,
# so a mismatch would silently misalign every per-layer result.
if [ -f "${FEAT}/train/manifest.json" ] && [ -f "${FEAT}/test/manifest.json" ]; then
  echo "[P1   ] per-layer features present; reusing ${FEAT}"
else
  echo
  echo "=================================================================="
  echo "[P1   ] extracting per-layer CLIP ViT-H-14 features (train + test)"
  echo "=================================================================="
  "${PY}" -u scripts/nwret/extract_layers.py --split both \
    --out "${FEAT}" --batch 64 --workers 8 2>&1 | tee "${LOGS}/extract_layers.log"
  rc=${PIPESTATUS[0]}
  if [ "${rc}" != "0" ]; then
    echo "[FATAL] layer extraction failed (rc=${rc}); the target scan is not possible"
    exit 1
  fi
fi

# ------------------------------------------------------------------ P2: probe
if [ -f "${OUT}/probe_layers.json" ]; then
  echo "[P2   ] alignment-layer probe present; reusing"
else
  echo
  echo "=================================================================="
  echo "[P2   ] alignment-layer probe (ridge, val-selected)"
  echo "=================================================================="
  "${PY}" -u scripts/nwret/probe_layers.py --subject "${SUBJ}" --features "${FEAT}" \
    --out "${OUT}/probe_layers.json" 2>&1 | tee "${LOGS}/probe_layers.log"
fi
PROBE_LAYER="$("${PY}" -c "
import json
try:
    print(json.load(open('${OUT}/probe_layers.json'))['best_by_val']['layer'])
except Exception:
    print('')")"
if [ -z "${PROBE_LAYER}" ]; then
  echo "[FATAL] probe produced no selection; nothing to align to"
  exit 1
fi
echo "[P2   ] probe-selected alignment layer: ${PROBE_LAYER}"
echo "[P2   ] reported lever: middle layers beat the final layer; see probe_layers.json"

# ------------------------------------------------------------------ P3..P7
# EXTRA stays empty throughout: every arm states its own regime, so a difference
# between two arms is attributable to the named axis and not to an inherited flag.
phase "P3 alignment-target scan (the confirmed lever)"   T22 T28
phase "P4 image-side multi-layer alignment"              MTmean MTrouted
phase "P5 EEG-encoder depth"                             E04 E08
phase "P6 EEG-side multi-layer fusion"                   FEU FER
phase "P7 tokenisation"                                  K49 K98

# ------------------------------------------------------------------ P8: summary
echo
echo "########## P8 summary @ $(date -Iseconds) (elapsed $(elapsed_h)h) ##########"
"${PY}" -u scripts/nwret/summarize.py \
  --out-dir "${OUT}" \
  --json "${OUT}/leaderboard.json" \
  --md "${OUT}/leaderboard.md" \
  --sota-top1 91.3 --sota-top5 98.8 --sota-name "SAMGA intra 17ch" || true

# The three specific questions, stated explicitly so they do not have to be
# reconstructed from the leaderboard.
OUT="${OUT}" PROBE_LAYER="${PROBE_LAYER}" ARM_LIST="$(bash scripts/run_arm.sh list | grep -v '^F[12]$' | tr '\n' ' ')" \
"${PY}" - <<'PY' || true
import json, os, pathlib
out = pathlib.Path(os.environ["OUT"])
probe_layer = os.environ["PROBE_LAYER"]
meta = {
    "T22": ("target scan block22", "target-layer"),
    "T28": ("target scan block28", "target-layer"),
    "MTmean": ("image-side fusion mean 22/24/26/28", "target-fusion"),
    "MTrouted": ("image-side fusion routed 22/24/26/28", "target-fusion"),
    "E04": ("EEG depth 4", "eeg-depth"),
    "E08": ("EEG depth 8", "eeg-depth"),
    "FEU": ("EEG fusion uniform 8/10/12", "eeg-fusion"),
    "FER": ("EEG fusion routed 8/10/12", "eeg-fusion"),
    "K49": ("tokenisation 49", "tokenisation"),
    "K98": ("tokenisation 98", "tokenisation"),
}

def load(p):
    p = out / p
    return json.loads(p.read_text()) if p.is_file() else None

def tag_of(arm):
    # Mirror run_arm.sh's mapping; kept explicit so the summary cannot silently
    # attribute a number to the wrong arm.
    return {"T22": "align_block22", "T28": "align_block28",
            "MTmean": "target_fuse_mean", "MTrouted": "target_fuse_routed",
            "E04": "eeg_l04", "E08": "eeg_l08", "FEU": "eeg_fuse_uniform",
            "FER": "eeg_fuse_routed", "K49": "tok49", "K98": "tok98"}.get(arm, arm)

ridge = (load("baseline_ridge.json") or {}).get("test", {}).get("top1")
pa = load(f"align_{probe_layer}_result.json")
f2 = load("F2_aug_only_result.json")

print()
print("=" * 96)
print("ANSWERS TO THE THREE QUESTIONS THIS RUN WAS BUILT TO SETTLE")
print("=" * 96)
print(f"  ridge floor (linear, same split)          : {ridge if ridge is None else round(ridge, 2)}")

def line(label, d):
    if not d:
        return f"  {label:42}: (not completed)"
    t, bv = d["test"], d.get("best_val", {})
    gap = "n/a"
    h = d.get("history") or []
    if h and bv.get("top1") is not None:
        gap = f"{h[-1]['train_top1_inbatch'] - bv['top1']:.0f}"
    return (f"  {label:42}: test {t['top1']:5.2f}  top5 {t['top5']:5.2f}  "
            f"rank {t['mean_rank']:5.1f}  val {bv.get('top1', float('nan')):5.2f}  gap {gap}")

print()
print("  [1] Is the alignment-target peak an optimum or a flat band?")
base = pa["test"]["top1"] if pa else None
line(f"{probe_layer} (current best)", pa)
for a in ("T22", "T28"):
    d = load(f"{tag_of(a)}_result.json")
    line(meta[a][0], d)
    if d and base is not None:
        print(f"  {'':42}  delta vs {probe_layer}: {d['test']['top1'] - base:+.2f}")

print()
print("  [2] Does aligning to SEVERAL image layers beat the best single one?")
line(f"single {probe_layer}", pa)
for a in ("MTmean", "MTrouted"):
    d = load(f"{tag_of(a)}_result.json")
    line(meta[a][0], d)
    if d:
        tw = d.get("target_weights")
        if tw:
            print(f"  {'':42}  learned target weights: "
                  f"{[round(v, 3) for v in tw]} over {d.get('target_layers')}")
        if d.get("target_fusion") == "routed" and tw and max(tw) > 0.7:
            print(f"  {'':42}  -> routing collapsed onto one layer: the layers are NOT")
            print(f"  {'':42}     complementary under this objective, whatever the score says")

print()
print("  [3] Does the EEG encoder's own depth matter (the doc's phase 1)?")
line("EEG depth 12 (all arms so far)", pa)
for a in ("E04", "E08"):
    line(meta[a][0], load(f"{tag_of(a)}_result.json"))

print()
print("  [4] EEG-side multi-layer fusion (the doc's phase 2):")
line("EEG depth 12, single layer", pa)
for a in ("FEU", "FER"):
    d = load(f"{tag_of(a)}_result.json")
    line(meta[a][0], d)
    if d and d.get("eeg_layer_weights"):
        print(f"  {'':42}  layer weights: {d['eeg_layer_weights']} over {d.get('layers')}")

print()
print("  [5] Tokenisation:")
line("196 tokens (all arms so far)", pa)
for a in ("K49", "K98"):
    line(meta[a][0], load(f"{tag_of(a)}_result.json"))

print()
print("  Reference points: final-layer target = "
      f"{f2['test']['top1'] if f2 else 'n/a'}, SOTA (SAMGA intra 17ch) = 91.30")
h = (pa or {}).get("history")
if h:
    print(f"  Generalisation gap on the best arm: train {h[-1]['train_top1_inbatch']:.1f} "
          f"vs val {pa['best_val']['top1']:.1f}. Note the earlier finding: the SMALLEST gap")
    print(f"  arm (F4, 12 pts) scored the WORST test number, so overfitting is not the")
    print(f"  binding constraint here. Do not read these numbers as a regularisation story.")
print()
PY

echo
echo "########## pipeline done @ $(date -Iseconds) (elapsed $(elapsed_h)h) ##########"
echo "results : ${OUT}"
echo "logs    : ${LOGS}"
echo "board   : ${OUT}/leaderboard.md"
