#!/usr/bin/env bash
# Arm dispatcher for the NW-Retrieval sub-08 study.
#
# DO NOT EDIT THIS FILE (or run_pipeline.sh) WHILE A JOB IS RUNNING IT. bash reads
# shell scripts incrementally by byte offset, so an edit mid-run makes the next read
# land in the middle of a changed region and the job dies on a bogus syntax error.
# That is how the 595261 summary phase was lost; its arm results survived on disk.
#
# Axis map -- there are TWO independent "layer" axes and conflating them was the
# bug that made the first sweep uninterpretable:
#
#   --target-layer(s)   which layer of the FROZEN IMAGE tower the EEG must match.
#                       This is the confirmed lever: block26 vs the final layer was
#                       +13.00 test Top-1 (34.00 vs 21.00) at fixed everything else.
#   --layers            which depth of the EEG ENCODER emits the feature that gets
#                       aligned. This is the axis the doc's phase 1 describes, and
#                       it was never tested under a working regime.
#
# Per-arm tags are the single source of truth for resumability, so they encode the
# variable being tested. Duplicating them in the pipeline would silently break
# resume (the arm would re-run forever, because the file it checks is never made).
set -uo pipefail

ROOT="/project/peilab/why/eeg-retrieval"
PY="${PYTHON:-/project/peilab/why/eeg-brainit/.venv/bin/python}"
cd "${ROOT}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
export HOME="${XDG_CACHE_HOME:-/project/peilab/why/cache/xdg}"
mkdir -p outputs/slurm

# F1/F2/PA are complete and are kept so the pipeline can cite them as controls.
# Order here is documentation only; the pipeline sets the run order.
ARMS=(F1 F2 PA T22 T28 MTmean MTrouted E04 E08 FEU FER K49 K98)

list_arms() { printf '%s\n' "${ARMS[@]}"; }

arm_tag() {
  case "$1" in
    F1)       echo F1_control_unfixed ;;
    F2)       echo F2_aug_only ;;
    # Tagged by the layer, because "the best layer" is a different experiment once
    # the probe result changes. Without this a re-run would skip the new layer.
    PA)       echo "align_${PROBE_LAYER:-unset}" ;;
    # --- the alignment-target scan, extending the confirmed lever
    T22)      echo align_block22 ;;
    T28)      echo align_block28 ;;
    # --- image-side multi-layer alignment
    MTmean)   echo target_fuse_mean ;;
    MTrouted) echo target_fuse_routed ;;
    # --- EEG-encoder depth (the doc's phase 1, on the other axis)
    E04)      echo eeg_l04 ;;
    E08)      echo eeg_l08 ;;
    # --- EEG-encoder multi-layer fusion (the doc's phase 2)
    FEU)      echo eeg_fuse_uniform ;;
    FER)      echo eeg_fuse_routed ;;
    # --- tokenisation
    K49)      echo tok49 ;;
    K98)      echo tok98 ;;
    *)        echo "" ;;
  esac
}

# Short human label for the leaderboard / summary lines.
arm_note() {
  case "$1" in
    F1)       echo "control: no augmentation, final-layer target (reproduces the broken sweep)" ;;
    F2)       echo "control for PA: augmentation on, final-layer target" ;;
    PA)       echo "probe-selected target ${PROBE_LAYER:-unset}, EEG depth 12" ;;
    T22)      echo "target scan: block22" ;;
    T28)      echo "target scan: block28" ;;
    MTmean)   echo "image-side fusion: mean over 22/24/26/28" ;;
    MTrouted) echo "image-side fusion: learned weights over 22/24/26/28" ;;
    E04)      echo "EEG-encoder depth 4" ;;
    E08)      echo "EEG-encoder depth 8" ;;
    FEU)      echo "EEG-side fusion: uniform over 8/10/12" ;;
    FER)      echo "EEG-side fusion: routed over 8/10/12" ;;
    K49)      echo "tokenisation: 49 tokens (1 time window)" ;;
    K98)      echo "tokenisation: 98 tokens (2 time windows)" ;;
    *)        echo "" ;;
  esac
}

ARM="${ARM:-list}"
CH="${CH:-occipito_parietal}"
SUBJ="${SUBJ:-8}"
EPOCHS="${EPOCHS:-50}"
OUT="${ROOT}/outputs/sub$(printf '%02d' "${SUBJ}")"
EXTRA="${EXTRA:-}"
FEAT="${FEAT:-${ROOT}/outputs/features/clip_h14_layers}"

common=(
  --subject "${SUBJ}"
  --channels "${CH}"
  --val-concepts 150
  --epochs "${EPOCHS}"
  --out-dir "${OUT}"
)

# Everything the winning config had, minus the two variables under test (which each
# arm states for itself). Kept as a bash array rather than a string so that word
# splitting cannot silently mangle a flag.
base=(
  --backbone timm:vit_b16_in21k
  --aug full
  --target-features "${FEAT}"
)

run() {
  local tag="$1"; shift
  local expect
  expect="$(arm_tag "${ARM}")"
  if [ -z "${expect}" ]; then
    echo "[arm ${ARM}] ERROR: no tag mapping for this arm" >&2
    return 2
  fi
  if [ "${tag}" != "${expect}" ]; then
    echo "[arm ${ARM}] ERROR: tag '${tag}' != arm_tag '${expect}'" >&2
    return 2
  fi
  echo "=================================================================="
  echo "[arm ${ARM}] tag=${tag}  $(arm_note "${ARM}")"
  echo "  $(date -Iseconds)"
  echo "  arm-specific : $*"
  echo "  regime EXTRA : ${EXTRA:-<none>}"
  echo "=================================================================="
  # shellcheck disable=SC2086  # EXTRA is intentionally word-split
  if [ -n "${DRY_RUN:-}" ]; then
    # Validate the real flag list without a GPU, the dataset, or a download. The
    # pipeline's dry run calls this for every arm, so a typo in any arm's flags is
    # caught before submission rather than hours into a job.
    "${PY}" -u scripts/nwret/train.py "${common[@]}" --tag "${tag}" "$@" ${EXTRA} --validate-only
    local rc=$?
    echo "[arm ${ARM}] dry-run rc=${rc}"
    return "${rc}"
  fi
  # shellcheck disable=SC2086  # EXTRA is intentionally word-split
  # --tag must be passed explicitly. It was validated above and then dropped, so
  # train.py fell back to its own default ({backbone}_L{layers}) and every arm
  # sharing --layers wrote to the same result JSON -- which also broke resumability,
  # because the pipeline looks for {arm_tag}_result.json.
  "${PY}" -u scripts/nwret/train.py "${common[@]}" --tag "${tag}" "$@" ${EXTRA}
  local rc=$?
  echo "[arm ${ARM}] rc=${rc} @ $(date -Iseconds)"
  return "${rc}"
}

case "${ARM}" in
  list) list_arms ;;

  # Prints the descriptive tag for an arm, so the pipeline owns no copy of it.
  tag) arm_tag "${1:-}" ;;

  # Prints the one-line description, for the pipeline's summary.
  note) arm_note "${1:-}" ;;

  # ---------------- controls (complete; the pipeline skips them) --------------
  # F1 is the unfixed configuration under the corrected validation metric. Its test
  # Top-1 (20.00) reproduces the original sweep exactly, which is what licenses
  # reading the other arms' differences as effects of their changes.
  F1) run F1_control_unfixed --backbone timm:vit_b16_in21k --layers 12 --aug none ;;

  # F2 is the control for PA: same everything, but aligned to the final layer
  # (_pooled), which is where every pre-PA arm pointed. So PA vs F2 isolates the
  # alignment target and nothing else (+13.00 measured).
  #
  # F2's flags are its ORIGINAL ones, not `base`: its recorded result (21.00) was
  # produced against the cached feature file, and re-invoking it with
  # --target-features would write a different config record for the same number.
  # A control whose provenance does not match its record is not a control.
  F2) run F2_aug_only --backbone timm:vit_b16_in21k --layers 12 --aug full ;;

  # PA = the winning configuration so far: EEG encoder depth 12, aligned to block26.
  PA)
    if [ -z "${PROBE_LAYER:-}" ]; then
      echo "[arm PA] ERROR: PROBE_LAYER is unset -- run probe_layers.py first" >&2
      exit 2
    fi
    run "align_${PROBE_LAYER}" "${base[@]}" --layers 12 --target-layer "${PROBE_LAYER}" ;;

  # ---------------- image-side alignment target scan --------------------------
  # The probe's ridge curve rises from block01 (4.87) through a peak at block26
  # (17.33) and falls to block32 (16.47), with block21..32 all above the final layer.
  # The deep model put block26 at 34.00 vs the final layer's 21.00, i.e. a much
  # bigger effect than the ridge curve implied. Two more depths bracket the peak:
  # if 22 and 28 both land near 34.00 the band is flat and the exact depth is not
  # critical; if they fall off, 26 is a genuine optimum worth fusing around.
  T22) run align_block22 "${base[@]}" --layers 12 --target-layer block22 ;;
  T28) run align_block28 "${base[@]}" --layers 12 --target-layer block28 ;;

  # ---------------- image-side multi-layer alignment (doc phase 2) ------------
  # The four layers span the probe's high band {22,24,26,28}. All are 1280-d, which
  # is required: blending happens before the projection, so they must share a width.
  MTmean)
    run target_fuse_mean "${base[@]}" --layers 12 \
      --target-layers block22 block24 block26 block28 --target-fusion mean ;;
  MTrouted)
    run target_fuse_routed "${base[@]}" --layers 12 \
      --target-layers block22 block24 block26 block28 --target-fusion routed ;;

  # ---------------- EEG-encoder depth (the doc's phase 1, other axis) ---------
  # PA ran at depth 12, the last block. The two earlier B-arms that scanned depth
  # were run under the broken regime (MMD on, softplus on) and landed below the
  # ridge floor, so their flat profile says nothing about the encoder. This reruns
  # the axis with the regime and alignment target now known to work.
  E04) run eeg_l04 "${base[@]}" --layers 4 --target-layer block26 ;;
  E08) run eeg_l08 "${base[@]}" --layers 8 --target-layer block26 ;;

  # ---------------- EEG-side multi-layer fusion (the doc's phase 2) -----------
  # uniform first: does EEG-side depth carry complementary information at all?
  # routed second, prior centred on the depth that won the single-layer scan above
  # (doc section 5.3: initialise the prior's centre on the scanned optimum rather
  # than at uniform, because a uniform prior spends mass on depths known to be poor).
  FEU) run eeg_fuse_uniform "${base[@]}" --layers 8 10 12 --fusion-mode uniform \
         --target-layer block26 ;;
  FER) run eeg_fuse_routed "${base[@]}" --layers 8 10 12 --fusion-mode routed \
         --prior-center 12 --prior-strength 1.0 --target-layer block26 ;;

  # ---------------- tokenisation ----------------------------------------------
  # n_tokens = grid_h * grid_w * n_time_windows, so this axis is free to vary here.
  # PA effectively ran 196 tokens (7 x 28). EEGiT prices tokenisation as a large
  # lever, and it is not confounded by capacity the way depth and width are.
  K49) run tok49 "${base[@]}" --layers 12 --n-time-windows 1 --target-layer block26 ;;
  K98) run tok98 "${base[@]}" --layers 12 --n-time-windows 2 --target-layer block26 ;;

  *) echo "unknown ARM=${ARM}"; echo "available:"; list_arms; exit 2 ;;
esac
