#!/usr/bin/env python
"""
A0 -- SYNTHETIC VALIDATION OF RSCA                          [GATE 1: no-go if fail]

Question: does the estimator recover a KNOWN neural-visible rank r* from data
generated by the model in docs/01_theory_and_plan.md section 1.2?

If it cannot recover r* on synthetic data where the truth is known, then no
result on real EEG is interpretable, and the project stops here.

MODEL GENERATED (docs 1.2)
    c_i       = sqrt(s_c) * A z_i    + sqrt(1-s_c) * private_c
    e_i^(t)   = sqrt(s_e) * D z_i    + sqrt(1-s_e) * private_e   (+ trial noise)
    z ~ N(0, I_ktrue),  A, D random with unit-norm columns

r* = k_true by construction.  The private parts are deliberately HIGH RANK
(artefacts / subject identity in real EEG) so the test runs in the
private-domination regime of Martens et al. that defeats disentanglement.

SNR PARAMETERISATION (why it changed)
    The first version scaled shared and private parts by independent constants.
    The implied SNR was an uninterpretable product of them, and the defaults
    happened to give ~2e-4 -- undetectable.  The estimator correctly returned
    k*=0 and the run looked like a bug when the test was simply unreasonable.
    Now snr_c / snr_e are the explicit shared variance FRACTIONS, both views
    have unit total variance, and rho_pop = sqrt(snr_c*snr_e) is the population
    canonical correlation the estimator must beat.

PREREGISTERED CRITERIA (docs C1)
    specificity: k_true=0  -> k_hat=0
    sensitivity: k_hat within +/-1 of r* once rho_pop is above the null
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib_rsca import cca_ridge, rsca  # noqa: E402


def make_problem(
    rng: np.random.Generator,
    *,
    n: int,
    T: int,
    p: int,
    q: int,
    k_true: int,
    snr_c: float = 1.0,
    snr_e: float = 1.0,
    k_private_c: int = 50,
    k_private_e: int = 50,
):
    """Generate (E, C) from the model.  Returns E (n,T,p), C (n,q), truth dict.

    snr_c, snr_e are the fraction of each view's variance that is shared.  NOTE
    that sqrt(snr_c*snr_e) is NOT the canonical correlation of this model, and
    the two differ by a large factor.  Assuming they were equal was a labelling
    error that made a correctly-working estimator look broken.  The real
    canonical correlation is much larger for two structural reasons:

      (1) PROJECTION FRACTION.  A unit-norm test direction sees only ~k_priv/dim
          of the private variance, not all of it, because the private component
          is spread over many dimensions.  For q=256, k_priv=50 that is ~0.2; for
          p=3000 it is ~0.017.
      (2) TRIAL-AVERAGING GAIN T.  Whitening uses the SINGLE-TRIAL residual
          covariance, whereas the concept mean's noise covariance is (1/T) times
          that.  The shared component lives in the mean and is unaffected, so
          the effective SNR gains a factor T=10.

    Both are real properties of EEG-mean CCA, not artefacts of the simulation,
    and (2) is why averaging repetitions is so valuable.  The gate therefore uses
    the EMPIRICAL held-out rho on the known-true components rather than a closed
    form.  `snr_geomean` is reported only as the raw design parameter.
    """
    if k_true > 0:
        A = rng.standard_normal((q, k_true)) / np.sqrt(q)
        D = rng.standard_normal((p, k_true)) / np.sqrt(p)
        Z = rng.standard_normal((n, k_true))
        shared_c = Z @ A.T                                    # (n, q)
        shared_e = np.einsum("nk,pk->np", Z, D)[:, None, :].repeat(T, 1)  # (n,T,p)
    else:
        shared_c = np.zeros((n, q))
        shared_e = np.zeros((n, T, p))

    # ---- private parts: unit variance, high effective rank -----------------
    kc = max(k_private_c, 1)
    priv_c = rng.standard_normal((n, kc)) @ \
        (rng.standard_normal((q, kc)) / np.sqrt(q)).T
    priv_c = priv_c / max(priv_c.std(), 1e-12)

    ke = max(k_private_e, 1)
    F = rng.standard_normal((p, ke)) / np.sqrt(p)
    priv_e = np.einsum("ntk,pk->ntp", rng.standard_normal((n, T, ke)), F)
    priv_e = priv_e + rng.standard_normal((n, T, p)) / np.sqrt(p)
    priv_e = priv_e / max(priv_e.std(), 1e-12)

    def _unit(x: np.ndarray) -> np.ndarray:
        s = x.std()
        return x / s if s > 1e-12 else x

    C = (np.sqrt(snr_c) * _unit(shared_c)
         + np.sqrt(max(1.0 - snr_c, 0.0)) * priv_c)
    E = (np.sqrt(snr_e) * _unit(shared_e)
         + np.sqrt(max(1.0 - snr_e, 0.0)) * priv_e)

    return (E.astype(np.float32), C.astype(np.float32),
            {"k_true": int(k_true), "n": int(n), "T": int(T),
             "snr_c": float(snr_c), "snr_e": float(snr_e),
             "snr_geomean": float(np.sqrt(snr_c * snr_e)),
             "proj_frac_c": float(min(k_private_c, q) / q),
             "proj_frac_e": float(min(k_private_e, p) / p),
             "trial_gain_T": int(T)})


def naive_cca_rank(E: np.ndarray, C: np.ndarray, thresh: float = 0.5) -> int:
    """Baseline: in-sample CCA on raw features, count components above a fixed
    threshold.  This is what a naive analysis reports; A0 exists to show how
    badly it is fooled by the spurious floor (docs Prop. 4(i))."""
    Eb = E.mean(1)
    n = Eb.shape[0]
    r = cca_ridge(Eb, C, K=max(2, min(50, n - 2)))
    return int((r.rho > thresh).sum())


def run(args) -> dict:
    out = {"config": vars(args), "sweeps": [], "null_cache_info": {}}
    t0 = time.time()

    # ------------------------------------------------------------------
    # NULL CACHING (essential for tractability)
    #
    # A CCA fit at the target size costs ~130 ms, so n_perm=1000 per config x
    # hundreds of configs is ~8.5 h.  But under the permutation null the
    # statistic's distribution is governed by the SHAPE (n, d, q, K, ridge), not
    # by the signal strength: permuting the concept labels of C destroys the
    # correspondence regardless of the (k_true, snr) that generated the data.
    # We therefore compute ONE null per n and reuse it, which is ~30x faster.
    #
    # This approximation was validated independently in selfcheck_lib.py (T3ii):
    # the held-out threshold obeys tau*sqrt(n) ~ 3.45 with NO dependence on p or q,
    # so shape is indeed the governing quantity.  We still record the null's
    # median/99th/max percentiles so any deviation is visible in the results.
    # ------------------------------------------------------------------
    nulls: Dict[int, Dict] = {}

    for n in args.n_list:
        rng = np.random.default_rng(9001 + n)
        E0, C0, _ = make_problem(
            rng, n=n, T=args.T, p=args.p, q=args.q, k_true=max(1, args.k_true_list[-1]),
            snr_c=0.3, snr_e=0.3,
            k_private_c=args.k_priv_c, k_private_e=args.k_priv_e)
        w0 = EEGWhitener(D=args.D).fit(E0)
        X0 = w0.transform_trials_flat(E0)[:, : E0.shape[1] // 2].mean(1)
        tn = time.time()
        nl = permutation_null(X0, C0, K=args.K, ridge=args.ridge,
                              n_perm=(40 if args.quick else args.n_perm),
                              alpha=args.alpha, rng=np.random.default_rng(n))
        nulls[n] = nl
        out["null_cache_info"][str(n)] = {
            "threshold": float(nl["threshold"]), "p50": float(np.quantile(nl["max_rho"], 0.5)),
            "p99": float(np.quantile(nl["max_rho"], 0.99)), "max": float(nl["max_rho"].max()),
            "tau_sqrt_n": float(nl["threshold"] * np.sqrt(n)),
            "seconds": round(time.time() - tn, 1), "n_perm": nl["n_perm"],
        }
        print(f"  [null cached] n={n:5d} thr={nl['threshold']:.4f} "
              f"p99={np.quantile(nl['max_rho'],0.99):.4f} "
              f"tau*sqrt(n)={nl['threshold']*np.sqrt(n):.2f} "
              f"({out['null_cache_info'][str(n)]['seconds']}s)", flush=True)

    for k_true in args.k_true_list:
        for snr in args.snr_list:
            for n in args.n_list:
                seeds = []
                for sd in range(args.seeds):
                    rng = np.random.default_rng(hash((k_true, round(snr, 6), n, sd)) % 2**31)
                    E, C, truth = make_problem(
                        rng, n=n, T=args.T, p=args.p, q=args.q, k_true=k_true,
                        snr_c=snr, snr_e=snr,
                        k_private_c=args.k_priv_c, k_private_e=args.k_priv_e,
                    )
                    r = rsca(E, C, D=args.D, K=args.K, ridge=args.ridge,
                             alpha=args.alpha, seed=sd, null=nulls[n])
                    s = r.summary()
                    s["naive_rank"] = naive_cca_rank(E, C, args.naive_thresh)
                    s["rho_cv_sym_top8"] = [round(float(x), 4) for x in r.rho_cv_sym[:8]]
                    s["rho_insample_top8"] = [round(float(x), 4) for x in r.rho_insample[:8]]
                    s["snr_geomean"] = truth["snr_geomean"]
                    seeds.append(s)

                # empirical held-out rho on the KNOWN-true components: this is the
                # quantity the gate thresholds on, since the closed form is not
                # sqrt(snr_c*snr_e) (see make_problem docstring)
                rho_true_emp = float(np.mean([
                    np.mean(s["rho_cv_sym_top8"][:k_true]) for s in seeds
                ])) if k_true > 0 else float("nan")

                k_hats = np.array([s["k_star"] for s in seeds], float)
                naives = np.array([s["naive_rank"] for s in seeds], float)
                err = np.abs(k_hats - k_true)
                row = {
                    "k_true": int(k_true), "snr": float(snr), "n": int(n),
                    "snr_geomean": float(seeds[0]["snr_geomean"]),
                    "rho_true_empirical": rho_true_emp,
                    "k_hat_mean": float(k_hats.mean()),
                    "k_hat_std": float(k_hats.std()),
                    "abs_err_mean": float(err.mean()),
                    "pass_seeds": int((err <= 1).sum()),
                    "threshold_mean": float(np.mean([s["threshold"] for s in seeds])),
                    "seeds": seeds,
                    "naive_rank_mean": float(naives.mean()),
                    "naive_abs_err_mean": float(np.abs(naives - k_true).mean()),
                }
                out["sweeps"].append(row)
                print(f"  k*={k_true:2d} snr={snr:<6.3f} n={n:5d} (rho_true={row['rho_true_empirical']:.3f})"
                      f" -> k_hat={row['k_hat_mean']:5.2f}+-{row['k_hat_std']:.2f}"
                      f" |err|={row['abs_err_mean']:.2f} pass={row['pass_seeds']}/{args.seeds}"
                      f"   [naive CCA: {row['naive_rank_mean']:.0f}]", flush=True)

    # ------------------------------ gates ---------------------------------
    need = max(1, int(np.ceil(0.8 * args.seeds)))
    spec = [r for r in out["sweeps"] if r["k_true"] == 0]
    sens = [r for r in out["sweeps"] if r["k_true"] > 0
            and (r["rho_true_empirical"] >= args.rho_detect
                 or r["rho_true_empirical"] != r["rho_true_empirical"])]
    spec_ok = sum(r["pass_seeds"] >= need for r in spec)
    sens_ok = sum(r["pass_seeds"] >= need for r in sens)

    out["gate"] = {
        "criterion": f"|k_hat-r*|<=1 for >={need}/{args.seeds} seeds",
        "specificity_configs": [len(spec), spec_ok],
        "sensitivity_configs": [len(sens), sens_ok],
        "specificity_pass": bool(spec and spec_ok == len(spec)),
        "sensitivity_pass": bool(sens and sens_ok >= max(1, int(np.ceil(0.8 * len(sens))))),
        "mean_abs_err_rsca": float(np.mean([r["abs_err_mean"] for r in out["sweeps"]])),
        "mean_abs_err_naive_cca": float(np.mean([r["naive_abs_err_mean"] for r in out["sweeps"]])),
        "elapsed_s": round(time.time() - t0, 1),
    }
    out["gate"]["verdict"] = ("PASS" if (out["gate"]["specificity_pass"]
                                         and out["gate"]["sensitivity_pass"])
                              else "FAIL")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="/project/peilab/why/eeg-retrieval/alignment/outputs/a0")
    ap.add_argument("--seeds", type=int, default=5)
    ap.add_argument("--n-list", type=int, nargs="+", default=[500, 1654])
    ap.add_argument("--k-true-list", type=int, nargs="+", default=[0, 1, 3, 8])
    ap.add_argument("--snr-list", type=float, nargs="+",
                    default=[0.01, 0.05, 0.20, 0.60],
                    help="shared variance fraction (both views)")
    ap.add_argument("--rho-detect", type=float, default=0.15,
                    help="only require recovery once the EMPIRICAL held-out rho on "
                         "the true components exceeds the permutation threshold")
    ap.add_argument("--T", type=int, default=10)
    ap.add_argument("--p", type=int, default=63 * 250)
    ap.add_argument("--q", type=int, default=1024)
    ap.add_argument("--D", type=int, default=400)
    ap.add_argument("--K", type=int, default=32)
    ap.add_argument("--ridge", type=float, default=1e-3)
    ap.add_argument("--n-perm", type=int, default=1000)
    ap.add_argument("--alpha", type=float, default=0.05)
    ap.add_argument("--k-priv-c", type=int, default=50)
    ap.add_argument("--k-priv-e", type=int, default=50)
    ap.add_argument("--naive-thresh", type=float, default=0.5)
    ap.add_argument("--quick", action="store_true")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    print("=" * 100)
    print("A0 -- synthetic validation of RSCA   [GATE 1]")
    print(f"     p={args.p} q={args.q} T={args.T} D={args.D} K={args.K} "
          f"n_perm={40 if args.quick else args.n_perm} quick={args.quick}")
    print("=" * 100)

    res = run(args)
    with open(os.path.join(args.out, "a0_results.json"), "w") as f:
        json.dump(res, f, indent=2)

    g = res["gate"]
    print("\n" + "=" * 100)
    print(f"GATE 1 VERDICT: {g['verdict']}")
    print(f"  specificity (r*=0 -> k_hat=0): {g['specificity_configs'][1]}/"
          f"{g['specificity_configs'][0]} configs   "
          f"{'PASS' if g['specificity_pass'] else 'FAIL'}")
    print(f"  sensitivity (detectable r*):   {g['sensitivity_configs'][1]}/"
          f"{g['sensitivity_configs'][0]} configs   "
          f"{'PASS' if g['sensitivity_pass'] else 'FAIL'}")
    print(f"  mean |k_hat - r*| :  RSCA = {g['mean_abs_err_rsca']:.2f}   "
          f"naive in-sample CCA = {g['mean_abs_err_naive_cca']:.2f}")
    print(f"  elapsed = {g['elapsed_s']}s")
    print(f"  wrote {os.path.join(args.out, 'a0_results.json')}")
    print("=" * 100)
    return 0 if g["verdict"] == "PASS" else 3


if __name__ == "__main__":
    sys.exit(main())
